name: PR Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    branches:
      - main

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const versionLabels = labels.filter(label => ['major', 'minor', 'patch'].includes(label));
            
            if (versionLabels.length === 0) {
              core.setFailed('PR must have exactly one version label: major, minor, or patch');
            } else if (versionLabels.length > 1) {
              core.setFailed('PR must have exactly one version label, found: ' + versionLabels.join(', '));
            } else {
              console.log('✅ Found valid version label:', versionLabels[0]);
            }

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build extension
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run e2e tests
        run: npm run test:e2e:headless
